import { ScientificEvidence } from '../types/science';

export const EVIDENCE_REGISTRY: Record<string, ScientificEvidence> = {
  MIFFLIN_1990: {
    citationId: 'MIFFLIN_1990',
    shortCitation: 'Mifflin et al. (1990)',
    fullTitle: 'A new predictive equation for resting energy expenditure in healthy individuals',
    journal: 'The American Journal of Clinical Nutrition, 51(2), 241-247',
    year: 1990,
    evidenceLevel: 'RCT',
    keyFinding: 'Mifflin-St Jeor equation predicted REE within 10% of measured calorimetry in 82% of non-obese and 70% of obese individuals, outperforming Harris-Benedict.',
    limitations: ['Does not directly account for skeletal muscle mass', 'High variance in competitive athletes with extreme body compositions'],
  },
  KATCH_MCARDLE_1996: {
    citationId: 'KATCH_MCARDLE_1996',
    shortCitation: 'Katch & McArdle (1996)',
    fullTitle: 'Exercise Physiology: Energy, Nutrition, and Human Performance',
    journal: 'Lippincott Williams & Wilkins',
    year: 1996,
    evidenceLevel: 'COHORT',
    keyFinding: 'BMR calculated from fat-free mass (FFM) provides superior estimation across athletic populations with known body composition.',
    limitations: ['Requires validated body composition assessment (DEXA or hydrostatic) to obtain true lean mass'],
  },
  GABBETT_2016_ACWR: {
    citationId: 'GABBETT_2016_ACWR',
    shortCitation: 'Gabbett, T. J. (2016)',
    fullTitle: 'The training—injury prevention paradox: should athletes be training smarter and harder?',
    journal: 'British Journal of Sports Medicine, 50(5), 273-280',
    year: 2016,
    evidenceLevel: 'COHORT',
    keyFinding: 'Acute:Chronic Workload Ratios (ACWR) between 0.8 and 1.3 are generally associated with adaptive conditioning, whereas acute spikes > 1.5 indicate rapid loading.',
    limitations: ['ACWR is a workload monitoring framework, NOT an individual injury diagnostic or deterministic predictor', 'Requires minimum 28 continuous days of workload data for chronic baseline'],
  },
  EPLEY_1985_1RM: {
    citationId: 'EPLEY_1985_1RM',
    shortCitation: 'Epley, B. (1985)',
    fullTitle: 'Poundage chart: Boyd Epley workout',
    journal: 'Lincoln, NE: Body Enterprises',
    year: 1985,
    evidenceLevel: 'COHORT',
    keyFinding: '1RM = Weight * (1 + 0.0333 * Reps). Validated for submaximal resistance efforts between 2 and 10 repetitions.',
    limitations: ['Accuracy diminishes sharply above 10 repetitions due to anaerobic endurance variability'],
  },
  TANAKA_2001_HRMAX: {
    citationId: 'TANAKA_2001_HRMAX',
    shortCitation: 'Tanaka et al. (2001)',
    fullTitle: 'Age-predicted maximal heart rate revisited',
    journal: 'Journal of the American College of Cardiology, 37(1), 153-156',
    year: 2001,
    evidenceLevel: 'META_ANALYSIS',
    keyFinding: 'HRmax = 208 - (0.7 * Age) provides lower standard error (S_y.x ~10 bpm) than traditional Fox (220 - age) equation.',
    limitations: ['Individual biological variation of +/- 10-12 bpm standard deviation exists'],
  },
  MORTON_2018_PROTEIN: {
    citationId: 'MORTON_2018_PROTEIN',
    shortCitation: 'Morton et al. (2018)',
    fullTitle: 'A systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength in healthy adults',
    journal: 'British Journal of Sports Medicine, 52(6), 376-384',
    year: 2018,
    evidenceLevel: 'META_ANALYSIS',
    keyFinding: 'Protein intakes beyond ~1.62 g/kg/day (95% CI: 1.03-2.20) do not systematically yield further resistance-training induced gains in fat-free mass across general resistance-trained adults.',
    limitations: ['Energy deficit/hypocaloric phases may warrant elevated protein preservation up to 2.2-2.4 g/kg'],
  },
};
